# Generated by Django 4.2 on 2024-11-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='slug',
        ),
    ]
