# Generated by Django 4.2 on 2024-10-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Blog_Category', 'verbose_name_plural': 'Blog_Categories'},
        ),
    ]
