# Generated by Django 4.2 on 2024-10-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categories', '0002_alter_blogcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
    ]
