# Generated by Django 4.2 on 2024-10-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categories', '0003_alter_blogcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='name_e',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_s',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
