# Generated by Django 4.2 on 2024-10-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categories', '0004_blogcategory_name_e_blogcategory_name_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_e',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_s',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_ed',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
