# Generated by Django 4.2 on 2024-10-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categories', '0005_remove_blogcategory_name_e_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcategory',
            old_name='name_ed',
            new_name='name_es',
        ),
    ]
