# Generated by Django 4.2 on 2024-10-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categories', '0006_rename_name_ed_blogcategory_name_es'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_en',
        ),
    ]
