# Generated by Django 4.2 on 2024-10-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categories', '0007_remove_blogcategory_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
