# Generated by Django 4.2 on 2024-10-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categories', '0008_blogcategory_name_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_es',
        ),
    ]
