# Generated by Django 4.2 on 2024-10-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categories', '0009_remove_blogcategory_name_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='name_es',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
