# Generated by Django 4.2 on 2024-12-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_limit_commentpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
