# Generated by Django 4.2 on 2024-12-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='limit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
