export const GET_PROJECTS_LIST_SUCCESS = 'GET_PROJECTS_LIST_SUCCESS';
export const GET_PROJECTS_LIST_FAIL = 'GET_PROJECTS_LIST_FAIL';

export const GET_PROJECTS_LIST_CATEGORIES_SUCCESS = 'GET_PROJECTS_LIST_CATEGORIES_SUCCESS';
export const GET_PROJECTS_LIST_CATEGORIES_FAIL = 'GET_PROJECTS_LIST_CATEGORIES_FAIL';

export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL';
export const GET_PROJECTS_SEARCH_SUCCESS = 'GET_PROJECTS_SEARCH_SUCCESS';
export const GET_PROJECTS_SEARCH_FAIL = 'GET_PROJECTS_SEARCH_FAIL';

export const GET_AUTHOR_LIST_SUCCESS = 'GET_AUTHOR_LIST_SUCCESS';
export const GET_AUTHOR_LIST_FAIL = 'GET_AUTHOR_LIST_FAIL';