# Generated by Django 4.2 on 2025-03-31 01:10

import apps.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_quill.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='Required: Please enter a valid email address.', max_length=254, unique=True)),
                ('first_name', models.CharField(help_text='Required', max_length=255)),
                ('last_name', models.CharField(help_text='Required', max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=apps.users.models.user_profile_img)),
                ('description', django_quill.fields.QuillField(blank=True, help_text='Optional: Add a description of yourself, your abilities, or your career.', null=True)),
                ('description_en', django_quill.fields.QuillField(blank=True, help_text='Optional: Add a description of yourself, your abilities, or your career.', null=True)),
                ('description_es', django_quill.fields.QuillField(blank=True, help_text='Optional: Add a description of yourself, your abilities, or your career.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter phone number with country code', max_length=128, region=None)),
                ('other_contact', django_quill.fields.QuillField(blank=True, help_text='Optional: Add alternative social media links, phone numbers, or email addresses to contact you.', null=True, verbose_name='Other Contacts')),
                ('role', models.CharField(choices=[('SUPERUSER', 'Superuser'), ('STAFF', 'Staff'), ('ADMIN', 'Admin'), ('EDITOR', 'Editor')], default='EDITOR', help_text='Be careful when assigning the SUPERUSER role to someone.', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light1', 'Light1'), ('light2', 'Light2'), ('dark1', 'Dark1'), ('dark2', 'Dark2')], default='light', max_length=20)),
                ('email_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='nationality',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nationality', verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='specialism',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.speciality', verbose_name='Specialism'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
