# Generated by Django 4.2 on 2024-11-21 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='bio',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='bio_en',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='bio_es',
            new_name='description_es',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='alias',
            new_name='slug',
        ),
    ]
