# Generated by Django 4.2 on 2024-12-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_bio_useraccount_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_editor',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Superuser'), ('STAFF', 'Staff'), ('ADMIN', 'Admin'), ('EDITOR', 'Editor')], default='STAFF', max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
