export const GET_PROJECTS_CATEGORIES_SUCCESS = 'GET_PROJECTS_CATEGORIES_SUCCESS';
export const GET_PROJECTS_CATEGORIES_FAIL = 'GET_PROJECTS_CATEGORIES_FAIL';

export const GET_LANGUAGES_SUCCESS = 'GET_LANGUAGES_SUCCESS';
export const GET_LANGUAGES_FAIL = 'GET_LANGUAGES_FAIL';