# Generated by Django 4.2 on 2024-12-15 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_published', 'Project Published'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('comment', 'New Comment'), ('announcement', 'Announcement'), ('new_project', 'New Project'), ('limit_date', 'Limit Date'), ('add_user', 'Add User'), ('update_user', 'Update User'), ('delete_user', 'Delete User'), ('settings_mod', 'Settings Mod')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
