# Generated by Django 4.2 on 2024-12-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_published', 'Project Published'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('comment', 'New Comment'), ('announcement', 'Announcement'), ('new_project', 'New Project'), ('limit_date', 'Limit Date'), ('add_user', 'Add User'), ('update_user', 'Update User'), ('delete_user', 'Delete User'), ('settings_modifications', 'Settings Modifications')], max_length=25),
        ),
    ]
